# -*- coding: utf-8 -*-
"""to-do list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3XC6Bu9k8yLuMgInC7u1XdSOOW7jPtg
"""

# to-do list
tasks = []

# Add Task
def add_task():
    task = input("Enter task: ")
    tasks.append(task)
    print("Task added successfully!")

# View Tasks
def view_tasks():
    if len(tasks) == 0:
        print("No tasks available.")
    else:
        print("\nYour Tasks:")
        count = 1
        for task in tasks:
            print(count, ".", task)
            count += 1

# Update Task
def update_task():
    view_tasks()

    if len(tasks) == 0:
        return

    task_no = int(input("Enter task number to update: "))

    if task_no > 0 and task_no <= len(tasks):
        new_task = input("Enter new task: ")
        tasks[task_no - 1] = new_task
        print("Task updated successfully!")
    else:
        print("Invalid task number.")

# Delete Task
def delete_task():
    view_tasks()

    if len(tasks) == 0:
        return

    task_no = int(input("Enter task number to delete: "))

    if task_no > 0 and task_no <= len(tasks):
        tasks.pop(task_no - 1)
        print("Task deleted successfully!")
    else:
        print("Invalid task number.")

# Main Menu
while True:
    print("\n===== TO-DO LIST MENU =====")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Update Task")
    print("4. Delete Task")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_task()

    elif choice == "2":
        view_tasks()

    elif choice == "3":
        update_task()

    elif choice == "4":
        delete_task()

    elif choice == "5":
        print("Thank you!")
        break

    else:
        print("Invalid choice. Please try again.")